/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class one_papachi_macfuse4j_MacFuse4j */

#ifndef _Included_one_papachi_macfuse4j_MacFuse4j
#define _Included_one_papachi_macfuse4j_MacFuse4j
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     one_papachi_macfuse4j_MacFuse4j
 * Method:    mount
 * Signature: ([Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_one_papachi_macfuse4j_MacFuse4j_mount
        (JNIEnv *, jobject, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
